In [1]:
import pandas as pd

In [2]:
mydata=pd.read_csv(r"C:\Users\shiva\Desktop\Machine Learning\DataSets-master\BMI_male_female.csv")

In [3]:
mydata

     Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
5      Male     189     104      3
6      Male     147      92      5
7      Male     154     111      5
8      Male     174      90      3
9    Female     169     103      4
10     Male     195      81      2
11   Female     159      80      4
12   Female     192     101      3
13     Male     155      51      2
14     Male     191      79      2
15   Female     153     107      5
16   Female     157     110      5
17     Male     140     129      5
18     Male     144     145      5
19     Male     172     139      5
20     Male     157     110      5
21   Female     153     149      5
22   Female     169      97      4
23     Male     185     139      5
24   Female     172      67      2
25   Female     151      64      3
26     Male     190      95      3
27     Male     187      62      1
28   Female     163     159      5
29     Male     179     152      5
..      ...     ...     ...    ...
470    Male     147     142      5
471    Male     154     112      5
472  Female     178      65      2
473    Male     195     153      5
474  Female     167      79      3
475    Male     183     131      4
476  Female     164     142      5
477    Male     167      64      2
478  Female     151      55      2
479  Female     147     107      5
480  Female     155     115      5
481  Female     172     108      4
482  Female     142      86      5
483    Male     146      85      4
484  Female     188     115      4
485    Male     173     111      4
486  Female     160     109      5
487    Male     187      80      2
488    Male     198     136      4
489  Female     179     150      5
490  Female     164      59      2
491  Female     146     147      5
492  Female     198      50      0
493  Female     170      53      1
494    Male     152      98      5
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [4]:
numofmale=mydata[mydata["Gender"]=="Male"]

In [9]:
 len(numofmale)

245

In [10]:
overwgtmale=numofmale[numofmale["Index"]==3]

In [11]:
overwgtmale

    Gender  Height  Weight  Index
4     Male     149      61      3
5     Male     189     104      3
8     Male     174      90      3
26    Male     190      95      3
48    Male     161      72      3
80    Male     164      75      3
109   Male     149      66      3
115   Male     148      60      3
137   Male     194     108      3
146   Male     194     106      3
148   Male     195      98      3
151   Male     140      52      3
162   Male     192     101      3
179   Male     188     100      3
185   Male     165      80      3
201   Male     179      93      3
208   Male     191      96      3
226   Male     166      70      3
235   Male     170      81      3
240   Male     178      85      3
246   Male     182      98      3
250   Male     153      70      3
274   Male     178      83      3
278   Male     172      75      3
291   Male     183     105      3
316   Male     188      99      3
343   Male     179      83      3
355   Male     174      90      3
370   Male     151      62      3
379   Male     176      87      3
396   Male     187      96      3
469   Male     198     109      3

In [13]:
len(overwgtmale)

32

In [16]:
Index_Name=pd.Series(["Extremely Weak","Weak","Normal","Over Weight","Obesity","Extreme Obesity"])

In [17]:
Index_Name

0     Extremely Weak
1               Weak
2             Normal
3        Over Weight
4            Obesity
5    Extreme Obesity
dtype: object

In [19]:
#Encode Male=0 Female=1
mydata.Gender[mydata.Gender=="Male"]=0
mydata.Gender[mydata.Gender=="Female"]=1

C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [20]:
mydata

    Gender  Height  Weight  Index
0        0     174      96      4
1        0     189      87      2
2        1     185     110      4
3        1     195     104      3
4        0     149      61      3
5        0     189     104      3
6        0     147      92      5
7        0     154     111      5
8        0     174      90      3
9        1     169     103      4
10       0     195      81      2
11       1     159      80      4
12       1     192     101      3
13       0     155      51      2
14       0     191      79      2
15       1     153     107      5
16       1     157     110      5
17       0     140     129      5
18       0     144     145      5
19       0     172     139      5
20       0     157     110      5
21       1     153     149      5
22       1     169      97      4
23       0     185     139      5
24       1     172      67      2
25       1     151      64      3
26       0     190      95      3
27       0     187      62      1
28       1     163     159      5
29       0     179     152      5
..     ...     ...     ...    ...
470      0     147     142      5
471      0     154     112      5
472      1     178      65      2
473      0     195     153      5
474      1     167      79      3
475      0     183     131      4
476      1     164     142      5
477      0     167      64      2
478      1     151      55      2
479      1     147     107      5
480      1     155     115      5
481      1     172     108      4
482      1     142      86      5
483      0     146      85      4
484      1     188     115      4
485      0     173     111      4
486      1     160     109      5
487      0     187      80      2
488      0     198     136      4
489      1     179     150      5
490      1     164      59      2
491      1     146     147      5
492      1     198      50      0
493      1     170      53      1
494      0     152      98      5
495      1     150     153      5
496      1     184     121      4
497      1     141     136      5
498      0     150      95      5
499      0     173     131      5

[500 rows x 4 columns]

In [22]:
X_Input=mydata.drop("Index",axis=1)

In [23]:
X_Input

    Gender  Height  Weight
0        0     174      96
1        0     189      87
2        1     185     110
3        1     195     104
4        0     149      61
5        0     189     104
6        0     147      92
7        0     154     111
8        0     174      90
9        1     169     103
10       0     195      81
11       1     159      80
12       1     192     101
13       0     155      51
14       0     191      79
15       1     153     107
16       1     157     110
17       0     140     129
18       0     144     145
19       0     172     139
20       0     157     110
21       1     153     149
22       1     169      97
23       0     185     139
24       1     172      67
25       1     151      64
26       0     190      95
27       0     187      62
28       1     163     159
29       0     179     152
..     ...     ...     ...
470      0     147     142
471      0     154     112
472      1     178      65
473      0     195     153
474      1     167      79
475      0     183     131
476      1     164     142
477      0     167      64
478      1     151      55
479      1     147     107
480      1     155     115
481      1     172     108
482      1     142      86
483      0     146      85
484      1     188     115
485      0     173     111
486      1     160     109
487      0     187      80
488      0     198     136
489      1     179     150
490      1     164      59
491      1     146     147
492      1     198      50
493      1     170      53
494      0     152      98
495      1     150     153
496      1     184     121
497      1     141     136
498      0     150      95
499      0     173     131

[500 rows x 3 columns]

In [26]:
Y_Output=mydata["Index"]

In [27]:
Y_Output

0      4
1      2
2      4
3      3
4      3
5      3
6      5
7      5
8      3
9      4
10     2
11     4
12     3
13     2
14     2
15     5
16     5
17     5
18     5
19     5
20     5
21     5
22     4
23     5
24     2
25     3
26     3
27     1
28     5
29     5
      ..
470    5
471    5
472    2
473    5
474    3
475    4
476    5
477    2
478    2
479    5
480    5
481    4
482    5
483    4
484    4
485    4
486    5
487    2
488    4
489    5
490    2
491    5
492    0
493    1
494    5
495    5
496    4
497    5
498    5
499    5
Name: Index, dtype: int64

In [28]:
X_Input.shape

(500, 3)

In [29]:
X=X_Input.values.reshape(500,3)

In [30]:
Y=Y_Output.values.reshape(500,1)

In [31]:
X

array([[0, 174, 96],
       [0, 189, 87],
       [1, 185, 110],
       ...,
       [1, 141, 136],
       [0, 150, 95],
       [0, 173, 131]], dtype=object)

In [32]:
Y

array([[4],
       [2],
       [4],
       [3],
       [3],
       [3],
       [5],
       [5],
       [3],
       [4],
       [2],
       [4],
       [3],
       [2],
       [2],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [2],
       [3],
       [3],
       [1],
       [5],
       [5],
       [5],
       [1],
       [1],
       [5],
       [5],
       [4],
       [3],
       [4],
       [5],
       [2],
       [4],
       [5],
       [2],
       [5],
       [4],
       [2],
       [4],
       [4],
       [3],
       [5],
       [5],
       [1],
       [5],
       [4],
       [4],
       [3],
       [4],
       [5],
       [3],
       [5],
       [0],
       [5],
       [0],
       [2],
       [5],
       [5],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [5],
       [2],
       [3],
       [4],
       [4],
       [4],
       [4],
       [0],
       [3],
       [5],
       [3],
       [4],
       [5],
       [0],
       [5],
       [5],
       [5],
       [5],
       [5],
       [3],
       [3],
       [2],
       [4],
       [5],
       [4],
       [5],
       [1],
       [0],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [5],
       [4],
       [3],
       [4],
       [5],
       [4],
       [2],
       [4],
       [3],
       [2],
       [5],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [2],
       [5],
       [2],
       [5],
       [4],
       [5],
       [5],
       [5],
       [3],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [5],
       [4],
       [3],
       [5],
       [3],
       [3],
       [0],
       [3],
       [3],
       [5],
       [5],
       [4],
       [3],
       [5],
       [3],
       [4],
       [2],
       [2],
       [3],
       [5],
       [4],
       [2],
       [4],
       [5],
       [3],
       [2],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [4],
       [3],
       [5],
       [3],
       [3],
       [4],
       [4],
       [2],
       [3],
       [3],
       [5],
       [3],
       [5],
       [4],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5],
       [4],
       [4],
       [5],
       [5],
       [1],
       [3],
       [4],
       [4],
       [5],
       [4],
       [5],
       [4],
       [3],
       [4],
       [4],
       [5],
       [5],
       [5],
       [0],
       [5],
       [5],
       [5],
       [5],
       [5],
       [2],
       [5],
       [4],
       [5],
       [0],
       [5],
       [3],
       [4],
       [5],
       [5],
       [4],
       [2],
       [3],
       [3],
       [4],
       [3],
       [5],
       [5],
       [2],
       [5],
       [3],
       [2],
       [1],
       [5],
       [0],
       [5],
       [3],
       [5],
       [3],
       [4],
       [3],
       [5],
       [5],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [5],
       [5],
       [1],
       [5],
       [5],
       [4],
       [0],
       [3],
       [3],
       [4],
       [2],
       [3],
       [1],
       [1],
       [5],
       [5],
       [4],
       [4],
       [4],
       [4],
       [5],
       [2],
       [5],
       [4],
       [3],
       [3],
       [4],
       [5],
       [5],
       [2],
       [4],
       [3],
       [4],
       [5],
       [4],
       [2],
       [4],
       [5],
       [4],
       [5],
       [5],
       [1],
       [5],
       [5],
       [5],
       [5],
       [2],
       [2],
       [5],
       [3],
       [5],
       [4],
       [5],
       [4],
       [4],
       [5],
       [5],
       [4],
       [2],
       [2],
       [4],
       [3],
       [3],
       [5],
       [4],
       [2],
       [2],
       [2],
       [2],
       [5],
       [5],
       [4],
       [5],
       [3],
       [4],
       [4],
       [3],
       [4],
       [4],
       [2],
       [2],
       [5],
       [2],
       [2],
       [2],
       [2],
       [5],
       [0],
       [3],
       [4],
       [5],
       [1],
       [4],
       [1],
       [4],
       [5],
       [4],
       [5],
       [5],
       [3],
       [4],
       [5],
       [4],
       [3],
       [5],
       [1],
       [2],
       [4],
       [5],
       [5],
       [5],
       [5],
       [3],
       [5],
       [1],
       [4],
       [5],
       [5],
       [2],
       [5],
       [4],
       [3],
       [2],
       [2],
       [2],
       [2],
       [3],
       [5],
       [3],
       [3],
       [5],
       [3],
       [5],
       [3],
       [4],
       [2],
       [4],
       [4],
       [5],
       [2],
       [5],
       [5],
       [5],
       [1],
       [4],
       [5],
       [5],
       [5],
       [4],
       [5],
       [2],
       [5],
       [2],
       [1],
       [5],
       [5],
       [4],
       [1],
       [1],
       [4],
       [4],
       [4],
       [4],
       [2],
       [5],
       [5],
       [4],
       [2],
       [5],
       [5],
       [5],
       [1],
       [5],
       [4],
       [2],
       [5],
       [5],
       [4],
       [5],
       [4],
       [4],
       [5],
       [5],
       [5],
       [4],
       [5],
       [0],
       [2],
       [2],
       [4],
       [2],
       [4],
       [5],
       [4],
       [5],
       [1],
       [5],
       [2],
       [5],
       [3],
       [5],
       [5],
       [3],
       [5],
       [5],
       [2],
       [5],
       [3],
       [4],
       [5],
       [2],
       [2],
       [5],
       [5],
       [4],
       [5],
       [4],
       [4],
       [4],
       [5],
       [2],
       [4],
       [5],
       [2],
       [5],
       [0],
       [1],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5]], dtype=int64)

In [34]:
#data split
x_train=X[:350]
x_test=X[350:]
y_train=Y[:350]
y_test=Y[350:]

In [41]:
y_train.shape

(350, 1)

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
teacher=KNeighborsClassifier()

In [44]:
learner=teacher.fit(x_train,y_train)

C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':

In [45]:
p=learner.predict([[0,179,131]])

In [46]:
Index_Name[p]

5    Extreme Obesity
dtype: object

In [47]:
#Testing
ya=y_test
yp=learner.predict(x_test)

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
acc=accuracy_score(ya,yp)*100

In [50]:
acc

91.333333333333329