In [1]:
import pandas as pd

In [2]:
mydata=pd.read_csv(r"C:\Users\dell\Desktop\ML\DataSets-master\Data_MVLR.csv")

In [3]:
mydata

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.00,3571,1976,0.525,541
1,9.00,4092,1250,0.572,524
2,9.00,3865,1586,0.580,561
3,7.50,4870,2351,0.529,414
4,8.00,4399,431,0.544,410
5,10.00,5342,1333,0.571,457
6,8.00,5319,11868,0.451,344
7,8.00,5126,2138,0.553,467
8,8.00,4447,8577,0.529,464
9,7.00,4512,8507,0.552,498
10,8.00,4391,5939,0.530,580
11,7.50,5126,14186,0.525,471
12,7.00,4817,6930,0.574,525
13,7.00,4207,6580,0.545,508
14,7.00,4332,8159,0.608,566
15,7.00,4318,10340,0.586,635
16,7.00,4206,8508,0.572,603
17,7.00,3718,4725,0.540,714
18,7.00,4716,5915,0.724,865
19,8.50,4341,6010,0.677,640
20,7.00,4593,7834,0.663,649
21,8.00,4983,602,0.602,540
22,9.00,4897,2449,0.511,464
23,9.00,4258,4686,0.517,547
24,8.50,4574,2619,0.551,460
25,9.00,3721,4746,0.544,566
26,8.00,3448,5399,0.548,577
27,7.50,3846,9061,0.579,631
28,8.00,4188,5975,0.563,574
29,9.00,3601,4650,0.493,534
30,7.00,3640,6905,0.518,571
31,7.00,3333,6594,0.513,554
32,8.00,3063,6524,0.578,577
33,7.50,3357,4121,0.547,628
34,8.00,3528,3495,0.487,487
35,6.58,3802,7834,0.629,644
36,5.00,4045,17782,0.566,640
37,7.00,3897,6385,0.586,704
38,8.50,3635,3274,0.663,648
39,7.00,4345,3905,0.672,968
40,7.00,4449,4639,0.626,587
41,7.00,3656,3985,0.563,699
42,7.00,4300,3635,0.603,632
43,7.00,3745,2611,0.508,591
44,6.00,5215,2302,0.672,782
45,9.00,4476,3942,0.571,510
46,7.00,4296,4083,0.623,610
47,7.00,5002,9794,0.593,524

In [5]:
from sklearn.linear_model import LinearRegression

In [14]:
x_input=mydata.drop("Petrol_Consumption",axis=1)
x_input

    Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)
0         9.00            3571            1976                         0.525
1         9.00            4092            1250                         0.572
2         9.00            3865            1586                         0.580
3         7.50            4870            2351                         0.529
4         8.00            4399             431                         0.544
5        10.00            5342            1333                         0.571
6         8.00            5319           11868                         0.451
7         8.00            5126            2138                         0.553
8         8.00            4447            8577                         0.529
9         7.00            4512            8507                         0.552
10        8.00            4391            5939                         0.530
11        7.50            5126           14186                         0.525
12        7.00            4817            6930                         0.574
13        7.00            4207            6580                         0.545
14        7.00            4332            8159                         0.608
15        7.00            4318           10340                         0.586
16        7.00            4206            8508                         0.572
17        7.00            3718            4725                         0.540
18        7.00            4716            5915                         0.724
19        8.50            4341            6010                         0.677
20        7.00            4593            7834                         0.663
21        8.00            4983             602                         0.602
22        9.00            4897            2449                         0.511
23        9.00            4258            4686                         0.517
24        8.50            4574            2619                         0.551
25        9.00            3721            4746                         0.544
26        8.00            3448            5399                         0.548
27        7.50            3846            9061                         0.579
28        8.00            4188            5975                         0.563
29        9.00            3601            4650                         0.493
30        7.00            3640            6905                         0.518
31        7.00            3333            6594                         0.513
32        8.00            3063            6524                         0.578
33        7.50            3357            4121                         0.547
34        8.00            3528            3495                         0.487
35        6.58            3802            7834                         0.629
36        5.00            4045           17782                         0.566
37        7.00            3897            6385                         0.586
38        8.50            3635            3274                         0.663
39        7.00            4345            3905                         0.672
40        7.00            4449            4639                         0.626
41        7.00            3656            3985                         0.563
42        7.00            4300            3635                         0.603
43        7.00            3745            2611                         0.508
44        6.00            5215            2302                         0.672
45        9.00            4476            3942                         0.571
46        7.00            4296            4083                         0.623
47        7.00            5002            9794                         0.593

In [16]:
y_out=mydata["Petrol_Consumption"]

In [23]:
xx_input=x_input.values.reshape(-1,4)

In [24]:
yy_out=y_out.values.reshape(-1,1)

In [25]:
mydata.keys()

Index(['Petrol_tax', 'Average_income', 'Paved_Highways',
       'Population_Driver_licence(%)', 'Petrol_Consumption'],
      dtype='object')

In [26]:
xx_input.shape

(48, 4)

In [27]:
yy_out.shape

(48, 1)

In [28]:
x_train=xx_input[:40]
x_test=xx_input[40:]
y_train=yy_out[:40]
y_test=yy_out[40:]

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
teacher=LinearRegression()

In [31]:
learner=teacher.fit(x_train,y_train)

In [34]:
yp=learner.predict(x_test)
ypp=list(yp)
yaa=list(y_test)
xx_test=list(x_test)

In [35]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [36]:
np.sqrt(mean_squared_error(y_test,yp))

57.481259417417661